### ISSUE TITLE
Migrate to from grpc to @grpc/grpc-js

### ISSUE THREAD

**Issue by miclud** [nicolaspearson/grpc.ts.health.check#23]
Hi,
any chance to migrate from using grpc to @grpc/grpc-js?

> This library is now only receiving bug fixes and runtime compatibility updates. In April 2021 it will be deprecated and will no longer receive any updates. We recommend using @grpc/grpc-js instead.

Ref. https://www.npmjs.com/package/grpc

**Comment by miclud** [comment]
Closing the issue as this is not needed anymore.

**Comment by schwichti** [comment]
I extend an existing grpc service that uses `@grpc/grpc-js` and add the grpc health check protocol. I was trying to add `grpc-ts-health-check` to that package but it seems that mixing `grpc` and `@grpc/grpc-js`
@miclud: Did you find another solution that makes migrating `grpc-ts-health-check` to `@grpc/grpc-js` unnecessary?

**Comment by miclud** [comment]
Hi @schwichti,
I ended up implementing the health check in the project which used this package.
The project being migrated to `@grpc/grpc-js` it seemed unnecessary to keep the dependency on `grpc-ts-health-check` which would prevent the project from migrating.

The requirements for the health cehck are well defined here https://github.com/grpc/grpc-node/tree/master/packages/grpc-health-check
with service definition here https://github.com/grpc/grpc/blob/master/doc/health-checking.md
and then using https://github.com/nicolaspearson/grpc.ts.health.check/blob/master/src/index.ts#L30 as an example.

We already had setup to generate types which for Typescript so it was just a matter of putting it together.
I also just needed the `check` functionality so that probably simplified it.
